title: Thao Duyen Tran # your name (or website title) here
logo: "/images/anhthe.JPG?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 I am an aspiring data analytics learner, a tech junkie and an upcoming entrepreneur.
 I love to use interesting algorithms to analyze data and extract meaningful results. 
 Besides, I am passionate about education, investing and technology and currently continuing
 to equip myself with professional and academic experience in these sectors.  
  <br><br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
